import "./globals.css";
import Navbar from "./Navbar";
export const metadata = {
  title: "JsonPlaceHolder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen w-screen flex flex-col bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
